auto check poetry dep files upon PR

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -6,7 +6,22 @@ on:
     branches: [ main ]
 
 jobs:
+  check-dependency-files:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+      
+      - name: Check for uncommitted changes in pyproject.toml or poetry.lock
+        run: |
+          git diff --exit-code -- pyproject.toml poetry.lock || {
+            echo "ERROR: Uncommitted changes detected in pyproject.toml or poetry.lock."
+            echo "Please commit the changes and run 'make' to update requirements.txt before pushing again."
+            exit 1
+          }
+
   Test:
+    needs: check-dependency-files
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
